### ISSUE TITLE
Assignment 6-  Pattern 

### ISSUE THREAD

**Issue by 53bit23** [vtcbca/basic-programming-59bit23#2]
What is the purpose of using a loop in a star pattern program?

**Comment by 53bit23** [comment]
A loop helps repeat the printing of stars for each row, ensuring the pattern is generated correctly.

**Comment by 59bit23** [comment]
A loop helps repeat the printing of stars for each row, ensuring the pattern is generated correctly.

**Comment by 53bit23** [comment]
How do you control the number of rows in a star pattern?

**Comment by 59bit23** [comment]
You control the number of rows by taking user input for the number of rows and using a loop to print stars accordingly.

**Comment by 53bit23** [comment]
What is the difference between a for loop and a while loop for generating patterns?

**Comment by 59bit23** [comment]
A for loop is typically used when you know the number of iterations (rows), while a while loop is used when the stopping condition is based on dynamic input.

**Comment by 53bit23** [comment]
How can you change the shape of the pattern?

**Comment by 59bit23** [comment]
By adjusting the number of stars or the way they are printed (e.g., changing the direction of the stars or adjusting spacing).

**Comment by 53bit23** [comment]
Can you generate a pattern with a different character instead of *?

**Comment by 59bit23** [comment]
Yes, you can replace the * with any other character, such as #, @, or &.

**Comment by 53bit23** [comment]
thanks @59bit23.
