### ISSUE TITLE
Assignment-7  :

### ISSUE THREAD

**Issue by 52bit23** [vtcbca/basic-programming-59bit23#3]
How do you print numbers in increasing order in each row?

**Comment by 59bit23** [comment]
Use the range function in the inner loop to print sequential numbers.

**Comment by 52bit23** [comment]
What happens if the user enters a negative number?

**Comment by 59bit23** [comment]
The program should check for valid input and display an error if the number is negative.

**Comment by 52bit23** [comment]
How do you modify the program to start numbers from 1 in each row?

**Comment by 59bit23** [comment]
Simply reset the starting number to 1 at the beginning of each outer loop iteration.

**Comment by 52bit23** [comment]
Can you generate an inverted triangle pattern with numbers?

**Comment by 59bit23** [comment]
Yes, start with the maximum number of numbers in the first row and decrement in each subsequent row.

**Comment by 52bit23** [comment]
What happens if you use end="" incorrectly in the print statement?

**Comment by 59bit23** [comment]
The numbers might not align properly in rows, and the output will not look like a triangle.
